name: GitHub actions demo
run-name: Testing our GitHub actions

on: [push]

jobs:
  basic_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run custom action
        uses: ./path/to/your/action # Replace with the correct relative path to your custom action
