name: Event-based workflow execution

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "TRIGGERED the main branch workflow - event based"
      
      - name: Use reusable workflow
        uses: ./.github/workflows/reuseme.yml
        with:
          # Define any input variables if required by the reusable workflow
